### PR TITLE
restore original ipset support on Amlogic-ng

### PR DESCRIPTION
**Pull request by pedroapero**
As discussed with @arthur-liberman in https://github.com/CoreELEC/CoreELEC/commit/419aa8085d5adc6a1fcfccb636732a6e14dc6dbc#r39240483

Ipset support is wanted when exposing CoreELEC to the Internet, by at least me and another user (https://discourse.coreelec.org/t/ipset-kernel-modules/10249).

First fix (6f489925fc385f2f9b2b2a7d744552fc6bf7166e) is working (I was able to run ipset commands on 20200523 nightly) but not sufficient (can't create any set):
```
# /opt/sbin/ipset create test-set hash:ip
ipset v7.4: Kernel error received: set type not supported
```

### CODE REVIEW

**Comment by arthur-liberman** [comment]
@pedroapero Have you run `make oldconfig` to generate the updated config file?

**Comment by pedroapero** [comment]
@arthur-liberman no I haven't.

**Comment by arthur-liberman** [comment]
@pedroapero Then you'll need to do that before this PR can be merged.
Unpack linux with your changes, navigate to its folder and run ~`ARCH=aarch64 make oldconfig`~ `ARCH=arm64 make oldconfig`.
This will help you generate a valid Kconfig file, which you then copy into the linux.aarch64.conf file. That should be your final commit/pr.

**Comment by pedroapero** [comment]
@arthur-liberman I run `ARCH=amd64 make oldconfig` on latest https://github.com/CoreELEC/linux-amlogic (I couldn't find any source containing `./arch/aarch64`). Let me know if that's not correct.

As you can see it removed the `CONFIG_HID_XPADNEO=m` option, which looks weird to me!

**Comment by shantigilbert** [comment]
> As you can see it removed the CONFIG_HID_XPADNEO=m option, which looks weird to me!

Please do not remove that, its for Xbox one S pads using Bluetooth (and also has nothing to do with this PR)

**Comment by shantigilbert** [comment]
> I run `ARCH=amd64 make oldconfig`

did you tried to run `ARCH=aarch64 make oldconfig` ? or does it give you an error? if so, which ?

**Comment by vpeter4** [comment]
When changing kernel config you need to make changes not on CoreELEC linux folder separately but it must be done from CoreELEC build environment.
So first clone and build of CoreELEC is necessary.
After whole project is build you can change some linux kernel config options.

Change to linux build folder and run oldconfig and then menuconfig
```
cd build.CoreELEC-Amlogic-ng.arm-9.2-devel/linux-*
ARCH=arm64 make menuconfig
```
Change some options and save them.

Then make a diff between new _.config_ file in linux folder and _projects/Amlogic-ng/linux/linux.aarch64.conf_

You can skip unrelated changes like CONFIG_DEFAULT_HOSTNAME

The reason why you got removed _CONFIG_HID_XPADNEO_ is that this device is added from patch file
_projects/Amlogic-ng/patches/linux/linux-04-xpadneo.patch_ .

**Comment by pedroapero** [comment]
Allright, I'll do that asap (i'm still here ;-)).

**Comment by arthur-liberman** [comment]
@pedroapero any updates to this? Is this PR still needed? And did you run the commands recommended by vpeter?

**Comment by pedroapero** [comment]
@arthur-liberman hi, sorry I waited so long to take time on this!

So I compiled CoreELEC/CoreELEC with `PROJECT=Amlogic-ng make`.

I enabled the ipset options using `ARCH=arm64 make menuconfig` as pointed by @vpeter4, and no more `CONFIG_HID_XPADNEO` option was touched this time.

I checked-out `CONFIG_DEFAULT_HOSTNAME` which was set to «CoreELEC» though.

That looks correct to me (same as original before 419aa8085d5adc6a1fcfccb636732a6e14dc6dbc, and generated this time).

**Pull request merged**
