### PR TITLE
GPU AML - mali update to r7p0 - Subtitles fix - improve AML rendering

### PR DESCRIPTION
**Pull request by wrxtasy**
- Update Mali drivers to r7p0 thx to @kszaq 
- Fix S912 external .srt subtitles video stuttering by disabling Kodi dirty regions completely
- And as a consequence I'm now seeing much improved CPU software decoding performance and rendering on a AML S912 U9. 
- Should be good enough for smooth 1080p H264 Netflix and Amazon Video streaming.

Untested with AML Kodi Leia.

### CODE REVIEW

**Comment by adamg88** [comment]
Thanks for the PR @wrxtasy 

This was put into the latest devel build to get some feedback from forum users.

**Comment by boot2k3** [comment]
This pull doesn't have any regression comments on Leia test builds for S912. I think it can be added.
But I don't know if algorithmdirtyregions (kodi: advancedsettings.xml disable Dirty Regions completely to fix Subtitles) change required by default, it can be added as additional setting.

**Comment by afl1** [comment]
opengl-meson-t82x: 3b21f97  has some performance degradation on  4k HDR 60fps for text overlay . I tested it on high bitrate samples by Samsung and LG (https://drive.google.com/uc?export=download&id=0Bxj6TUyM3NwjNFNmTUJEVjZjMDA with Ctrl-Shift-O)

**Comment by wrxtasy** [comment]
>opengl-meson-t82x: 3b21f97 has some performance degradation on 4k HDR 60fps for text overlay . I tested it on high bitrate samples by Samsung and LG

I see the exact same Kodi fps performance fps degredation no matter which Chipset, set of GPU drivers or advancedsettings.xml used.

For example even 1080p without r7p0 will have video frame upsets when I pull up the OTA TV overlay.
It's a Kodi issue IMHO.

Also S912 CoreELEC is missing a needed libhybris patch I believe:
https://github.com/kszaq/LibreELEC.tv/blob/libreelec-8.2/packages/devel/libhybris/patches/libhybris-fbdev_window.patch

**Comment by adamg88** [comment]
@wrxtasy the libhybris patch is not needed for Leia as the patch was superseded and the changes upstreamed by kszaq before he left the scene.

I can't speak for the other issues as however osmc also tried the r7p0 changes and reverted back after regressions it caused.

**Comment by wrxtasy** [comment]
> the libhybris patch is not needed for Leia as the patch was superseded and the changes upstreamed by kszaq before he left the scene.

Please check the libhybris package hashes again, nothing from that patch was upstreamed by kszaq

We are going to have to agree to disagree it seems and that's fine.

**Comment by adamg88** [comment]
@wrxtasy it wasn't libhybris that the changes where upstreamed too it was Kodi hence I said the patch was superceeded, I will try to find the commit and link back

**Comment by adamg88** [comment]
@wrxtasy https://github.com/xbmc/xbmc/pull/13377

**Comment by wrxtasy** [comment]
Ahh thx. upstream xbmc. was looking  in the wrong place.

**Comment by DavideFioravanti** [comment]
@wrxtasy I compiled from your fork and later from master adding your patches but I didn't see any performance increase. Same poor performance in Netlifx even in 720p. How did you get the performance increase?
Thanks.

**Comment by Raybuntu** [comment]
There is no point leaving this open unnecessarily long. We don't see any benefits.

**Pull request closed without merging**
