### PR TITLE
Tvheadend43 bump

### PR DESCRIPTION
**Pull request by JimmyS83**
Update to the 2af3b9e (master 2020.05.22), python3. Also updated dvb scan table included.

### CODE REVIEW

**Comment by Portisch** [comment]
I am sorry, my force push broke your PR. To fix it just fetch CoreELEC/coreelec-9.2 branch and make a rebase on your PR.

**Comment by JimmyS83** [comment]
> 
> 
> I am sorry, my force push broke your PR. To fix it just fetch CoreELEC/coreelec-9.2 branch and make a rebase on your PR.

Rebased.

**Comment by JimmyS83** [comment]
Could be merged maybe? Or is there any problem?

**Comment by cdu13a** [comment]
@JimmyS83 One of the developers will take a look when one of us gets a chance. The team is currently busy trying to deal with some infrastructure issues such as rebuilding a server getting our forum back online.

**Comment by JimmyS83** [comment]
Thank you for update. Sorry for hear that, wish you all non-problematic recovery and years without similiar problems :( I know that pain. [FluxBB](https://fluxbb.org/) or [SMF](https://www.simplemachines.org/) would be my wish, as Discourse is just waste of resources from user point of view :)

**Comment by JimmyS83** [comment]
As few months past by, I updated this a bit, since the PR wasnt merged yet.

**Comment by Raybuntu** [comment]
I see no reason why this could not be merged. If it works why not.

**Comment by Portisch** [comment]
@JimmyS83 can you please bump to last HEAD of TVH and confirm if it's still working?

**Comment by JimmyS83** [comment]
> @JimmyS83 can you please bump to last HEAD of TVH and confirm if it's still working?

I can do a bump, but for better testing I would need longer time period, as I dont watch DVB-T2 TV that much at all.. My relatives used this version more than half year, and so far no problems with it. But I suppose I could share binary addon on forum, I remember there were also some other users, which try/use it back then.

**Pull request closed without merging**
