### PR TITLE
Remove unmaintained RTL8812AU and RTL8814AU drivers, use aircrack-ng variant

### PR DESCRIPTION
**Pull request by kszaq**
These commits remove unmaintained RTL8812/4AU drivers and make projects use `aircrack-ng` variant.

Comparing hardware IDs, the `aircrank-ng` module covers all IDs from 8812au and 8814au, and 3 additional IDs:
```
diff --git a/8812_8814.txt b/8812_new.txt
index 4daf91a..80760d0 100755
--- a/8812_8814.txt
+++ b/8812_new.txt
@@ -14,6 +14,7 @@ usb:v056Ep400Fd*dc*dsc*dp*ic*isc*ip*in*
 usb:v0586p3426d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0789p016Ed*dc*dsc*dp*ic*isc*ip*in*
 usb:v07B8p8812d*dc*dsc*dp*ic*isc*ip*in*
+usb:v0846p9051d*dc*dsc*dp*ic*isc*ip*in*^M
 usb:v0846p9052d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0846p9054d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0B05p17D2d*dc*dsc*dp*ic*isc*ip*in*
@@ -34,6 +35,7 @@ usb:v0BDApA811d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0DF6p0074d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0E66p0022d*dc*dsc*dp*ic*isc*ip*in*
 usb:v0E66p0023d*dc*dsc*dp*ic*isc*ip*in*
+usb:v0E66p0026d*dc*dsc*dp*ic*isc*ip*in*^M
 usb:v1058p0632d*dc*dsc*dp*ic*isc*ip*in*
 usb:v13B1p003Fd*dc*dsc*dp*ic*isc*ip*in*
 usb:v148Fp9097d*dc*dsc*dp*ic*isc*ip*in*
@@ -68,3 +70,4 @@ usb:v7392pA813d*dc*dsc*dp*ic*isc*ip*in*
 usb:v7392pA822d*dc*dsc*dp*ic*isc*ip*in*
 usb:v7392pA833d*dc*dsc*dp*ic*isc*ip*in*
 usb:v7392pA834d*dc*dsc*dp*ic*isc*ip*in*
+usb:v7392pB611d*dc*dsc*dp*ic*isc*ip*in*
```

### CODE REVIEW

**Review by Portisch — COMMENTED** [review]
Is the driver supported kernel 5.4? Now it was only for 4.9 kernel.

**Comment by kszaq** [comment]
LibreELEC uses it for kernels 6+, should be fine with 5.4.

**Comment by Portisch** [comment]
5.15 does fail:
```text
/home/portisch/CE/CoreELEC/build.CoreELEC-Amlogic-no.aarch64-21/build/RTL8812AU-eee82ac1401e211a58a42cd89ab788b4f55040af/os_dep/linux/ioctl_cfg80211.c:468:17: error: too few arguments to function 'cfg80211_ch_switch_started_notify'
  468 |                 cfg80211_ch_switch_started_notify(adapter->pnetdev, &chdef, 0, false);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The problem is this and some other "bad" switch: https://github.com/aircrack-ng/rtl8812au/blob/v5.13.6/os_dep/linux/ioctl_cfg80211.c#L467C41-L467C41

**Comment by Portisch** [comment]
[fix_for _5.15.78.zip](https://github.com/CoreELEC/CoreELEC/files/13450006/fix_for._5.15.78.zip)
Can you please check if the driver still build fine for 4.9 with these patches?
If yes please include them in `/patches` package sub directory for the PR, thx.

**Comment by kszaq** [comment]
Can we instead put patches in `projects/Amlogic-ce/devices/Amlogic-ne/patches`?

**Comment by Portisch** [comment]
This would require to keep the Amlogic package and bump it to same status like the LE used one.
Then there the Amlogic project specific changes can be added.

**Comment by Portisch** [comment]
> Can we instead put patches in `projects/Amlogic-ce/devices/Amlogic-ne/patches`?

Actually I don't know and will try it later if it works.
But can you confirm it works for 4.9 when these patches are included?

**Comment by kszaq** [comment]
Sorry, but these patches do not apply cleanly to `eee82ac1401e211a58a42cd89ab788b4f55040af` revision nor `v5.6.4.2` branch tip, even with the whitespace changes removed.

**Comment by vpeter4** [comment]
This patch applies on `eee82ac1401e211a58a42cd89ab788b4f55040af` and builds on all our kernels.

[0001-Fix-for-Amlogic-kernel-5.15.78.patch](https://github.com/CoreELEC/CoreELEC/files/13461682/0001-Fix-for-Amlogic-kernel-5.15.78.patch)

**Comment by Portisch** [comment]
Yes, this works for 5.15. Patch is applied and driver compiled.
```text
UNPACK      RTL8812AU
    APPLY PATCH (project)      projects/Amlogic-ce/patches/RTL8812AU/0001-Fix-for-Amlogic-kernel-5.15.78.patch
```

**Comment by kszaq** [comment]
Thank you, @vpeter4!

I can confirm that the driver builds and works with this patch. I was also able to test it with a TP-Link RTL8814AU dongle and with the updated driver performance is a bit more consistent - steady 250Mbps vs fluctuating between 100 and 250Mbps with old driver, measured this a few times switching the driver back and forth.

**Pull request merged**
