### PR TITLE
systemd: add variant of nokia 8010 remote to 70-local-keyboard.hwdb

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vpeter4** [comment]
Put it before `nvidia shield remotes` to be sorted by alphabetical.

**Comment by vpeter4** [comment]
You should made changes in this PR :(

**Comment by ghost** [comment]
For a better structure without an unnecessary number of commits, I created a new pull request.

This can be found here:
https://github.com/CoreELEC/CoreELEC/pull/337

**Comment by vpeter4** [comment]
What about if I would request something else in this second PR? You would open third one and then forth one? No, you should amend commit in this PR and force push it.

So you know for next time something like this: https://craigoda.medium.com/git-commit-amend-push-and-force-with-lease-b525937d5ded

**Comment by ghost** [comment]
Unfortunately I don't have much experience with GIT, please forgive me.

**Pull request closed without merging**
