### PR TITLE
Add cryptsetup package

### PR DESCRIPTION
**Pull request by doozan**
This is #271, but on 19.  As a bonus, 19 already has a libdevmapper package, so no need to duplicate that.

### CODE REVIEW

**Comment by vpeter4** [comment]
Header missing in cryptsetup package.mk.

**Comment by doozan** [comment]
Header added

**Comment by Raybuntu** [comment]
> Header added

Where?

**Comment by doozan** [comment]
On my local machine, apparently :)  It's there now.

**Comment by Portisch** [comment]
How to use this crypt package? Would there not be needed something in busybox/init script to decrypt the drive? How to encrypt the drive? Would be `COREELEC` partition also be encrypted?

**Comment by doozan** [comment]
The binary just gives makes it possible to create/open/close encrypted volumes, and it's probably most useful for users that want to attach encrypted media to their device. Here's a [short intro](https://linuxconfig.org/basic-guide-to-encrypting-linux-partitions-with-luks) on using it.

It's possible to encrypt COREELEC if you add a custom mount-storage.sh init script to handle the unlocking. See https://github.com/CoreELEC/CoreELEC/pull/212#issuecomment-511240178 for a very rough example script that starts sshd and waits to for the user to connect and unlock the volume.

**Comment by Portisch** [comment]
Closed by https://github.com/CoreELEC/CoreELEC/commit/3ee93100c8a862666484c42f17c366df3105d475
Thank you for your support!

**Pull request closed without merging**
