### PR TITLE
Tweak shaders for AML ARM platforms

### PR DESCRIPTION
**Pull request by wrxtasy**
Kodi PR#15286 improved rendering performance:
https://github.com/xbmc/xbmc/pull/15286

Further tweaks are needed for AML ARM platforms.
As suggest by @kszaq in the above PR.

Noticeable improvements, especially for S912 LE/CE users include:

1) 480/576i mpeg2 SW decoding and YADIF2x deinterlacing is now possible.
2) 720p h264 SW decoding and smooth playback when using Kodi Leia's Netflix Addon is now possible
3) No video playback / external subtitle stuttering observed now with S912 LE / CE

### CODE REVIEW

**Comment by adamg88** [comment]
Thanks @wrxtasy

**Comment by adamg88** [comment]
Thanks for the heads up

**Comment by adamg88** [comment]
@wrxtasy we have had reports that this does not solve the subtitle situation

**Comment by wrxtasy** [comment]
@kszaq did not notice anything, but I have also been testing fritsch's colorspace conversion improvements.

Did a back to back test and i cannot seen any differences to be honest. Will need to throw more SW decoded SD content at it methinks. I suspect it will be pretty rare finding any BT.601 video content to test.

Would be safer leaving such colorspace conversion enable for legacy video support.

Also updated the S912's t82x GPU drivers to your #3b21f97 and I swear during testing the GUI is a bit snappier vs what CoreELEC is currently using.

@adamg88 - only briefly tested. Will have another look. I am testing slightly diff OpenGLES S912 GPU drivers as well. (v3.2)

**Comment by adamg88** [comment]
@wrxtasy [this](https://discourse.coreelec.org/t/coreelec-8-99-1/3341/11) is one users comments who is quite familiar with the subtitle issue, I'm sure there was a reason we didn't update the GPU drivers but I can't remember off the top of my head

**Comment by wrxtasy** [comment]
The included advancedsettings.xml file in the last PR might have caused issues for non S912 users.

With rendering improvements now included in Kodi Leia updating AML S9xx OpenGLES drivers might be worth revisiting. 
Poor Kodi Leia ARM rendering performance I believe has been the main cause of numerous issues I've seen since Kodi Jarvis/Krypton LE releases.

**Comment by fritsch** [comment]
The above patch is wrong and makes no sense at all. Furthermore: Why do you guys still track patches?

**Comment by adamg88** [comment]
@fritsch we are using your powrevert now, I think everybody tracks patches.

**Comment by fritsch** [comment]
Everyone that cannot use git most likely :-)

Am Do., 31. Jan. 2019, 17:00 hat adamg88 <notifications@github.com>
geschrieben:

**Pull request merged**
