### PR TITLE
Add TBS 5930 config + update dvb-firmware

### PR DESCRIPTION
**Pull request by smp79**

### CODE REVIEW

**Comment by Portisch** [comment]
I get:
```diff
diff --git a/projects/Amlogic-ce/devices/Amlogic-no/linux/linux.aarch64.conf b/projects/Amlogic-ce/devices/Amlogic-no/linux/linux.aarch64.conf
index 699dde3c4e..9112319948 100644
--- a/projects/Amlogic-ce/devices/Amlogic-no/linux/linux.aarch64.conf
+++ b/projects/Amlogic-ce/devices/Amlogic-no/linux/linux.aarch64.conf
@@ -3754,6 +3754,7 @@ CONFIG_DVB_USB_AZ6027=m
 CONFIG_DVB_USB_TECHNISAT_USB2=m
 CONFIG_DVB_USB_TBS5520SE=m
 CONFIG_DVB_USB_TBS5580=m
+CONFIG_DVB_USB_TBS5930=m
 CONFIG_DVB_USB_V2=m
 CONFIG_DVB_USB_AF9015=m
 CONFIG_DVB_USB_AF9035=m
@@ -4031,6 +4032,7 @@ CONFIG_DVB_RTL2832=m
 CONFIG_DVB_SI2168=m
 CONFIG_DVB_AS102_FE=m
 CONFIG_DVB_ZD1301_DEMOD=m
+CONFIG_DVB_M88RS6060=m
 CONFIG_DVB_GP8PSK_FE=m
 ```

**Comment by smp79** [comment]
You want to add CONFIG_DVB_M88RS6060=m ? It should build anyway.

**Comment by Portisch** [comment]
Yes, please fix the config as we always have the full config.

**Comment by vpeter4** [comment]
Don't use `-w` to hide all the warnings because can still be useful.

If you don't want to fix the TBS driver sources then remove `-Werror` like this with sed
`+        -e 's|^\(KBUILD_CFLAGS    += -Werror\)|# \1|' \`

**Comment by smp79** [comment]
> -e 's|^\(KBUILD_CFLAGS += -Werror\)|# \1|' \

It does not compile with this

**Comment by vpeter4** [comment]
So there are still some real errors in the code?

If I understand correctly both currently open PR should build?

**Comment by smp79** [comment]
It builds with -w switch

**Pull request merged**
