### PR TITLE
Use BBR TCP congestion control

### PR DESCRIPTION
**Pull request by V10lator**
This is a pull request requested by @Portisch at https://discourse.coreelec.org/t/bbr-as-tcp-congestion-control-algorithm-for-ng-builds/14119/2?u=v10lator

### CODE REVIEW

**Comment by Portisch** [comment]
I am not sure if it is an improvement.
Three times without this PR merged:
```text
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 51282 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   168 MBytes   703 Mbits/sec    0   1.56 MBytes
[  5]   2.00-4.00   sec   202 MBytes   849 Mbits/sec   18   1.58 MBytes
[  5]   4.00-6.00   sec   186 MBytes   781 Mbits/sec    0   1.69 MBytes
[  5]   6.00-8.00   sec   120 MBytes   503 Mbits/sec   13   1.34 MBytes
[  5]   8.00-10.00  sec   129 MBytes   540 Mbits/sec    0   1.46 MBytes
[  5]  10.00-12.00  sec   219 MBytes   918 Mbits/sec    0   1.51 MBytes
[  5]  12.00-14.00  sec   224 MBytes   938 Mbits/sec    0   1.53 MBytes
[  5]  14.00-16.00  sec   220 MBytes   923 Mbits/sec    0   1.54 MBytes
[  5]  16.00-18.00  sec   221 MBytes   928 Mbits/sec    0   1.55 MBytes
[  5]  18.00-20.00  sec   225 MBytes   944 Mbits/sec    0   1.55 MBytes
[  5]  20.00-22.00  sec   224 MBytes   938 Mbits/sec    0   1.67 MBytes
[  5]  22.00-24.00  sec   224 MBytes   938 Mbits/sec    0   1.71 MBytes
[  5]  24.00-26.00  sec   224 MBytes   938 Mbits/sec    0   1.71 MBytes
[  5]  26.00-28.00  sec   225 MBytes   944 Mbits/sec    0   1.71 MBytes
[  5]  28.00-30.00  sec   224 MBytes   939 Mbits/sec    0   1.71 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  2.96 GBytes   848 Mbits/sec   31             sender
[  5]   0.00-30.00  sec  2.96 GBytes   847 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 51286 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   202 MBytes   846 Mbits/sec    0    966 KBytes
[  5]   2.00-4.00   sec   225 MBytes   944 Mbits/sec    0   1.03 MBytes
[  5]   4.00-6.00   sec   225 MBytes   944 Mbits/sec    0   1.08 MBytes
[  5]   6.00-8.00   sec   216 MBytes   907 Mbits/sec    0   1.43 MBytes
[  5]   8.00-10.00  sec   224 MBytes   938 Mbits/sec    0   1.43 MBytes
[  5]  10.00-12.00  sec   215 MBytes   902 Mbits/sec    0   1.77 MBytes
[  5]  12.00-14.00  sec   224 MBytes   938 Mbits/sec    0   1.77 MBytes
[  5]  14.00-16.00  sec   224 MBytes   938 Mbits/sec    0   1.88 MBytes
[  5]  16.00-18.00  sec   219 MBytes   917 Mbits/sec  333   1.81 MBytes
[  5]  18.00-20.00  sec   224 MBytes   938 Mbits/sec    4   1.32 MBytes
[  5]  20.00-22.00  sec   220 MBytes   923 Mbits/sec    0   1.49 MBytes
[  5]  22.00-24.00  sec   222 MBytes   933 Mbits/sec    0   1.52 MBytes
[  5]  24.00-26.00  sec   225 MBytes   944 Mbits/sec    0   1.52 MBytes
[  5]  26.00-28.00  sec   221 MBytes   928 Mbits/sec    0   1.60 MBytes
[  5]  28.00-30.00  sec   220 MBytes   923 Mbits/sec    0   1.60 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  3.23 GBytes   924 Mbits/sec  337             sender
[  5]   0.00-30.00  sec  3.23 GBytes   924 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 51290 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   210 MBytes   880 Mbits/sec    0    744 KBytes
[  5]   2.00-4.00   sec   224 MBytes   938 Mbits/sec    0    904 KBytes
[  5]   4.00-6.00   sec   219 MBytes   918 Mbits/sec    0   1.10 MBytes
[  5]   6.00-8.00   sec   225 MBytes   944 Mbits/sec    0   1.10 MBytes
[  5]   8.00-10.00  sec   224 MBytes   938 Mbits/sec    0   1.25 MBytes
[  5]  10.00-12.00  sec   225 MBytes   944 Mbits/sec    0   1.31 MBytes
[  5]  12.00-14.00  sec   222 MBytes   933 Mbits/sec    0   1.48 MBytes
[  5]  14.00-16.00  sec   218 MBytes   912 Mbits/sec    0   1.98 MBytes
[  5]  16.00-18.00  sec   225 MBytes   944 Mbits/sec    0   2.49 MBytes
[  5]  18.00-20.00  sec   219 MBytes   918 Mbits/sec  188   1.74 MBytes
[  5]  20.00-22.00  sec   224 MBytes   938 Mbits/sec    0   1.76 MBytes
[  5]  22.00-24.00  sec   224 MBytes   938 Mbits/sec    0   1.88 MBytes
[  5]  24.00-26.00  sec   219 MBytes   918 Mbits/sec   20   1.56 MBytes
[  5]  26.00-28.00  sec   224 MBytes   938 Mbits/sec    0   1.76 MBytes
[  5]  28.00-30.00  sec   216 MBytes   907 Mbits/sec    0   1.86 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  3.24 GBytes   927 Mbits/sec  208             sender
[  5]   0.00-30.00  sec  3.24 GBytes   927 Mbits/sec                  receiver

iperf Done.
```

With the PR merged:
```text
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 44886 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   199 MBytes   835 Mbits/sec    0    255 KBytes
[  5]   2.00-4.00   sec   208 MBytes   873 Mbits/sec    0    240 KBytes
[  5]   4.00-6.00   sec   189 MBytes   793 Mbits/sec    0    238 KBytes
[  5]   6.00-8.00   sec   192 MBytes   804 Mbits/sec    0    246 KBytes
[  5]   8.00-10.00  sec   207 MBytes   868 Mbits/sec    0    238 KBytes
[  5]  10.00-12.00  sec   210 MBytes   880 Mbits/sec    0    240 KBytes
[  5]  12.00-14.00  sec   207 MBytes   869 Mbits/sec    0    240 KBytes
[  5]  14.00-16.00  sec   207 MBytes   867 Mbits/sec    0    238 KBytes
[  5]  16.00-18.00  sec   202 MBytes   845 Mbits/sec    0    240 KBytes
[  5]  18.00-20.00  sec   210 MBytes   882 Mbits/sec    0    232 KBytes
[  5]  20.00-22.00  sec   202 MBytes   848 Mbits/sec    0    232 KBytes
[  5]  22.00-24.00  sec   214 MBytes   898 Mbits/sec    0    238 KBytes
[  5]  24.00-26.00  sec   205 MBytes   861 Mbits/sec    0    232 KBytes
[  5]  26.00-28.00  sec   207 MBytes   868 Mbits/sec    0    243 KBytes
[  5]  28.00-30.00  sec   196 MBytes   823 Mbits/sec    0    232 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  2.98 GBytes   854 Mbits/sec    0             sender
[  5]   0.00-30.00  sec  2.98 GBytes   854 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 44890 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   208 MBytes   872 Mbits/sec    0    252 KBytes
[  5]   2.00-4.00   sec   210 MBytes   882 Mbits/sec    0    252 KBytes
[  5]   4.00-6.00   sec   211 MBytes   883 Mbits/sec    0    243 KBytes
[  5]   6.00-8.00   sec   207 MBytes   870 Mbits/sec    0    235 KBytes
[  5]   8.00-10.00  sec   204 MBytes   854 Mbits/sec    0    243 KBytes
[  5]  10.00-12.00  sec   210 MBytes   882 Mbits/sec    0    243 KBytes
[  5]  12.00-14.00  sec   212 MBytes   889 Mbits/sec    0    243 KBytes
[  5]  14.00-16.00  sec   189 MBytes   792 Mbits/sec    0    277 KBytes
[  5]  16.00-18.00  sec   206 MBytes   865 Mbits/sec    0    246 KBytes
[  5]  18.00-20.00  sec   210 MBytes   880 Mbits/sec    0    252 KBytes
[  5]  20.00-22.00  sec   215 MBytes   900 Mbits/sec    0    235 KBytes
[  5]  22.00-24.00  sec   213 MBytes   892 Mbits/sec    0    249 KBytes
[  5]  24.00-26.00  sec   203 MBytes   851 Mbits/sec    0    249 KBytes
[  5]  26.00-28.00  sec   206 MBytes   866 Mbits/sec    0    238 KBytes
[  5]  28.00-30.00  sec   207 MBytes   867 Mbits/sec    0    238 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  3.04 GBytes   870 Mbits/sec    0             sender
[  5]   0.00-30.00  sec  3.04 GBytes   869 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 44894 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   187 MBytes   786 Mbits/sec    0    238 KBytes
[  5]   2.00-4.00   sec   190 MBytes   798 Mbits/sec    0    238 KBytes
[  5]   4.00-6.00   sec   194 MBytes   814 Mbits/sec    0    232 KBytes
[  5]   6.00-8.00   sec   194 MBytes   815 Mbits/sec    0    232 KBytes
[  5]   8.00-10.00  sec   192 MBytes   806 Mbits/sec    0    232 KBytes
[  5]  10.00-12.00  sec   170 MBytes   712 Mbits/sec    0    269 KBytes
[  5]  12.00-14.00  sec   198 MBytes   830 Mbits/sec    0    232 KBytes
[  5]  14.00-16.00  sec   195 MBytes   819 Mbits/sec    0    232 KBytes
[  5]  16.00-18.00  sec   199 MBytes   836 Mbits/sec    0    235 KBytes
[  5]  18.00-20.00  sec   191 MBytes   801 Mbits/sec    0    235 KBytes
[  5]  20.00-22.00  sec   187 MBytes   783 Mbits/sec    0    232 KBytes
[  5]  22.00-24.00  sec   198 MBytes   829 Mbits/sec    0    229 KBytes
[  5]  24.00-26.00  sec   190 MBytes   796 Mbits/sec    0    232 KBytes
[  5]  26.00-28.00  sec   178 MBytes   748 Mbits/sec    0    283 KBytes
[  5]  28.00-30.00  sec   201 MBytes   842 Mbits/sec    0    240 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  2.80 GBytes   801 Mbits/sec    0             sender
[  5]   0.00-30.00  sec  2.79 GBytes   800 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c 192.168.1.216 -i 2 -t 30
Connecting to host 192.168.1.216, port 5201
[  5] local 192.168.1.125 port 44898 connected to 192.168.1.216 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec   188 MBytes   788 Mbits/sec    0    238 KBytes
[  5]   2.00-4.00   sec   187 MBytes   786 Mbits/sec    0    232 KBytes
[  5]   4.00-6.00   sec   191 MBytes   803 Mbits/sec    0    226 KBytes
[  5]   6.00-8.00   sec   189 MBytes   792 Mbits/sec    0    226 KBytes
[  5]   8.00-10.00  sec   195 MBytes   817 Mbits/sec    0    240 KBytes
[  5]  10.00-12.00  sec   188 MBytes   787 Mbits/sec    0    226 KBytes
[  5]  12.00-14.00  sec   179 MBytes   753 Mbits/sec    0    308 KBytes
[  5]  14.00-16.00  sec   206 MBytes   863 Mbits/sec    0    235 KBytes
[  5]  16.00-18.00  sec   164 MBytes   688 Mbits/sec    0    235 KBytes
[  5]  18.00-20.00  sec   191 MBytes   803 Mbits/sec    0    240 KBytes
[  5]  20.00-22.00  sec   197 MBytes   825 Mbits/sec    0    240 KBytes
[  5]  22.00-24.00  sec   192 MBytes   804 Mbits/sec    0    243 KBytes
[  5]  24.00-26.00  sec   204 MBytes   854 Mbits/sec    0    238 KBytes
[  5]  26.00-28.00  sec   197 MBytes   828 Mbits/sec    0    229 KBytes
[  5]  28.00-30.00  sec   198 MBytes   830 Mbits/sec    0    221 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  2.80 GBytes   801 Mbits/sec    0             sender
[  5]   0.00-30.00  sec  2.80 GBytes   801 Mbits/sec                  receiver

iperf Done.
```

**Comment by V10lator** [comment]
It's mostly an improvement on weak networks (packet loss). Also maybe try the other way around.

**Comment by Portisch** [comment]
Yes, I have seen it. It's a "bit slower" but looks more stable with less errors, but the speed is decreased.

**Comment by arthur-liberman** [comment]
I'd also check how it affects CPU usage.
I don't think that the difference between 930 and 800 Mbps is that important, but it probably has some other effects on the system besides lower transfer rates.

**Comment by Portisch** [comment]
I tested it with my LTE internet connection as this shows pretty well a "unstable" connection:

without the PR merged:
```text
CoreELEC:~ # iperf3 -c bouygues.iperf.fr -i 2 -t 30
Connecting to host bouygues.iperf.fr, port 5201
[  5] local 192.168.1.125 port 52910 connected to 89.84.1.222 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec  1.20 MBytes  5.04 Mbits/sec    0   80.6 KBytes
[  5]   2.00-4.00   sec  1.12 MBytes  4.69 Mbits/sec    0    124 KBytes
[  5]   4.00-6.00   sec  1018 KBytes  4.17 Mbits/sec    0    168 KBytes
[  5]   6.00-8.00   sec  1.30 MBytes  5.47 Mbits/sec    0    264 KBytes
[  5]   8.00-10.00  sec  1.43 MBytes  5.99 Mbits/sec   25    356 KBytes
[  5]  10.00-12.00  sec   891 KBytes  3.65 Mbits/sec   62    328 KBytes
[  5]  12.00-14.00  sec   891 KBytes  3.65 Mbits/sec   17    246 KBytes
[  5]  14.00-16.00  sec   891 KBytes  3.65 Mbits/sec    0    279 KBytes
[  5]  16.00-18.00  sec   891 KBytes  3.65 Mbits/sec    0    288 KBytes
[  5]  18.00-20.00  sec   891 KBytes  3.65 Mbits/sec    0    291 KBytes
[  5]  20.00-22.00  sec   891 KBytes  3.65 Mbits/sec    0    315 KBytes
[  5]  22.00-24.00  sec  0.00 Bytes  0.00 bits/sec   22    223 KBytes
[  5]  24.00-26.00  sec   891 KBytes  3.65 Mbits/sec    1    287 KBytes
[  5]  26.00-28.00  sec   891 KBytes  3.65 Mbits/sec    0    332 KBytes
[  5]  28.00-30.00  sec   891 KBytes  3.65 Mbits/sec   24    243 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  13.9 MBytes  3.88 Mbits/sec  151             sender
[  5]   0.00-30.55  sec  12.5 MBytes  3.43 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c bouygues.iperf.fr -i 2 -t 30
Connecting to host bouygues.iperf.fr, port 5201
[  5] local 192.168.1.125 port 52914 connected to 89.84.1.222 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec  1.16 MBytes  4.85 Mbits/sec    0   80.6 KBytes
[  5]   2.00-4.00   sec  1.12 MBytes  4.69 Mbits/sec    0    127 KBytes
[  5]   4.00-6.00   sec  1.30 MBytes  5.47 Mbits/sec    0    178 KBytes
[  5]   6.00-8.00   sec  1.30 MBytes  5.47 Mbits/sec    0    273 KBytes
[  5]   8.00-10.00  sec  2.30 MBytes  9.64 Mbits/sec    0    478 KBytes
[  5]  10.00-12.00  sec   954 KBytes  3.91 Mbits/sec   92    351 KBytes
[  5]  12.00-14.00  sec  0.00 Bytes  0.00 bits/sec   11    263 KBytes
[  5]  14.00-16.00  sec  1.12 MBytes  4.69 Mbits/sec    0    303 KBytes
[  5]  16.00-18.00  sec   954 KBytes  3.91 Mbits/sec    0    324 KBytes
[  5]  18.00-20.00  sec   954 KBytes  3.91 Mbits/sec    0    328 KBytes
[  5]  20.00-22.00  sec   954 KBytes  3.91 Mbits/sec    0    337 KBytes
[  5]  22.00-24.00  sec  1.06 MBytes  4.43 Mbits/sec   14    247 KBytes
[  5]  24.00-26.00  sec   954 KBytes  3.91 Mbits/sec    0    307 KBytes
[  5]  26.00-28.00  sec   954 KBytes  3.91 Mbits/sec    0    334 KBytes
[  5]  28.00-30.00  sec  0.00 Bytes  0.00 bits/sec    8    223 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  15.0 MBytes  4.18 Mbits/sec  125             sender
[  5]   0.00-30.56  sec  13.3 MBytes  3.66 Mbits/sec                  receiver

iperf Done.
```

with the PR merged:
```text
CoreELEC:~ # iperf3 -c bouygues.iperf.fr -i 2 -t 30
Connecting to host bouygues.iperf.fr, port 5201
[  5] local 192.168.1.125 port 57734 connected to 89.84.1.222 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec  1.43 MBytes  6.01 Mbits/sec    0   82.0 KBytes
[  5]   2.00-4.00   sec  1018 KBytes  4.17 Mbits/sec    0   79.2 KBytes
[  5]   4.00-6.00   sec   764 KBytes  3.13 Mbits/sec    0   76.4 KBytes
[  5]   6.00-8.00   sec  1018 KBytes  4.17 Mbits/sec    0   79.2 KBytes
[  5]   8.00-10.00  sec  1018 KBytes  4.17 Mbits/sec    0   5.66 KBytes
[  5]  10.00-12.00  sec   764 KBytes  3.13 Mbits/sec    0   67.9 KBytes
[  5]  12.00-14.00  sec   764 KBytes  3.13 Mbits/sec    0   65.0 KBytes
[  5]  14.00-16.00  sec  1018 KBytes  4.17 Mbits/sec    0   65.0 KBytes
[  5]  16.00-18.00  sec   764 KBytes  3.13 Mbits/sec    0   65.0 KBytes
[  5]  18.00-20.00  sec  1018 KBytes  4.17 Mbits/sec    0   65.0 KBytes
[  5]  20.00-22.00  sec   509 KBytes  2.08 Mbits/sec    0   59.4 KBytes
[  5]  22.00-24.00  sec   764 KBytes  3.13 Mbits/sec    0   65.0 KBytes
[  5]  24.00-26.00  sec   764 KBytes  3.13 Mbits/sec    0   56.6 KBytes
[  5]  26.00-28.00  sec   764 KBytes  3.13 Mbits/sec    0   56.6 KBytes
[  5]  28.00-30.00  sec  1018 KBytes  4.17 Mbits/sec    0   65.0 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  13.1 MBytes  3.67 Mbits/sec    0             sender
[  5]   0.00-30.15  sec  12.5 MBytes  3.48 Mbits/sec                  receiver

iperf Done.
CoreELEC:~ # iperf3 -c bouygues.iperf.fr -i 2 -t 30
Connecting to host bouygues.iperf.fr, port 5201
[  5] local 192.168.1.125 port 57742 connected to 89.84.1.222 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-2.00   sec  1.44 MBytes  6.02 Mbits/sec    0   84.8 KBytes
[  5]   2.00-4.00   sec   764 KBytes  3.13 Mbits/sec    0   76.4 KBytes
[  5]   4.00-6.00   sec  1018 KBytes  4.17 Mbits/sec    0   76.4 KBytes
[  5]   6.00-8.00   sec  1018 KBytes  4.17 Mbits/sec    0   82.0 KBytes
[  5]   8.00-10.00  sec   827 KBytes  3.39 Mbits/sec    0   5.66 KBytes
[  5]  10.00-12.00  sec   764 KBytes  3.13 Mbits/sec    0   67.9 KBytes
[  5]  12.00-14.00  sec  1018 KBytes  4.17 Mbits/sec    0   65.0 KBytes
[  5]  14.00-16.00  sec  1.06 MBytes  4.43 Mbits/sec    0   73.5 KBytes
[  5]  16.00-18.00  sec  1018 KBytes  4.17 Mbits/sec    0   65.0 KBytes
[  5]  18.00-20.00  sec  1018 KBytes  4.17 Mbits/sec    0   73.5 KBytes
[  5]  20.00-22.00  sec  1018 KBytes  4.17 Mbits/sec    0   87.7 KBytes
[  5]  22.00-24.00  sec   954 KBytes  3.91 Mbits/sec    0   76.4 KBytes
[  5]  24.00-26.00  sec   954 KBytes  3.91 Mbits/sec    0   73.5 KBytes
[  5]  26.00-28.00  sec   954 KBytes  3.91 Mbits/sec    0   65.0 KBytes
[  5]  28.00-30.00  sec   954 KBytes  3.91 Mbits/sec    0   67.9 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  14.5 MBytes  4.05 Mbits/sec    0             sender
[  5]   0.00-30.15  sec  14.0 MBytes  3.89 Mbits/sec                  receiver

iperf Done.
```

**Comment by V10lator** [comment]
Now that you say it all I see is a more stable but slightly slower (fighting buferbloat?) connection, too. Will do some research.

**Comment by V10lator** [comment]
Could you repeat the test after executing `tc qdisc replace dev enp0s20f0 root netem latency 70ms` on both, server and client and `tc qdisc add dev eth0 root netem loss 1.5%` on the CoreELEC box? Ofc. change eth0 with your network interface.

Other than that: Could you handle me the .img file so I can benchmark on my end, too?

**Comment by Portisch** [comment]
Please use this test image:
https://mega.nz/file/GKJmUJqY#Fine8BDYkLGQQ-kv8mfd9D1od2aBw0M4IZTm3rh42Uc
It's like last nightly + the his PR merged.

**Comment by V10lator** [comment]
Sadly that image cashes for me even in savemode. If it's really just nightly + this patch this can be closed cause it's not stable enough at the kernel version used. If it crashed cause of some other cause there's this for benchmarking TCP CCAs: https://gitlab.lrz.de/tcp-bbr/measurement-framework

**Comment by V10lator** [comment]
There are also these benchmarking tools from google: https://github.com/google/bbr/tree/v2alpha/gtests/net/tcp/bbr/nsperf

**Comment by Portisch** [comment]
> Sadly that image cashes for me even in savemode. If it's really just nightly + this patch this can be closed cause it's not stable enough at the kernel version used.

Ok ,thank you for your contribution!
We are thinking merging this change is "not good" as it will limit the speed. For sure the band width stability is improved but I guess a lot of users have already high bitrate internet and so some errors are better than loss of speed (seen in average).

**Pull request closed without merging**
