### PR TITLE
Brutefir support for CoreElec

### PR DESCRIPTION
**Pull request by meijjaa**
Dear all,

I made this proposal to get Brutefir working with Kodi through a ALSA loopback device. This setup allows for a lot of possible filter solutions like equalizing / room correction. 

So far I only tested this on my S905W box with Toslink connection to my DAC, works very nicely with Librespot and other media. I was only able to get this working at 48khz output though (same when only using Kodi), not sure if this is a hardware limitation.

Kind regards,

### CODE REVIEW

**Comment by speedyburnzales** [comment]
Hey meijjaa, this is a cool feature! Could you please provide a small "how to" for dummies like me to get brutfir activated in Coreelec? That would be great. Thanks.

**Comment by speedyburnzales** [comment]
@meijjaa, are you still working on this project?

Regards speedy B.

**Comment by meijjaa** [comment]
> @meijjaa, are you still working on this project?
> 
> Regards speedy B.

Hi Speedy, not really working on it. But I'm using my branch as a daily driver for my audio system. Anything I can help you with?

**Comment by speedyburnzales** [comment]
Good to hear and thank you for offering to help me. I like to do some room correction using brutefir. I am familiar with getting the filter parameters (via REW), however I don't know how to get Coreelec to use brutefir? Is it running by default or do I have to modify some start-up scripts? How did you do your config? RegardsSpeedy B.

**Comment by meijjaa** [comment]
No problem. You can get the sample config files from here: https://github.com/meijjaa/CoreELEC/tree/brutefir-9.2/packages/audio/brutefir/config
Or on the device in: /usr/config/

Copy all the files to the correct /storage locations and remove the .sample suffix. After a reboot you should be able to select ALSA loopback device in "settings->system->audio->audio output device"

As you can see in the .brutefir_config file you will need two wav impulse files from the REW EQ, (https://www.audiosciencereview.com/forum/index.php?threads/brutefir-for-volumio-now-supports-rew-eq-filters.7722/)

Match these to your REW config:
filename: "/storage/ref meting R-filters-48k.wav";
	format: "S32_LE";
	skip:44;
	attenuation: 12;

You can also first try to start Brutefir via the terminal for easy debugging: /usr/bin/brutefir /storage/.config/.brutefir_config

Good luck!

**Comment by meijjaa** [comment]
I rebased my branch to the latest CE 9.2 code and added the brutefir example config.

**Comment by speedyburnzales** [comment]
Thanks a lot meijja, great guidance !!
 I will check it out this weekend:)

**Pull request closed without merging**
