### PR TITLE
Enabled sqlite ICU support.

### PR DESCRIPTION
**Pull request by Kurganov**
Enabled sqlite ICU support. This make case insensitive like statement for non ASCII characters.
+ Fix nfs-utils depends.

### CODE REVIEW

**Comment by Portisch** [comment]
What is the reason the `icu` package got moved?
`sqlite` build fine in same place.

**Comment by Kurganov** [comment]
Yes, build fine, but more logical place for the package is in `packages/textproc` than in `packages/addons/addon-depends/`. Or is it preferable to be backward compatible with libreelec?

**Comment by Portisch** [comment]
Maybe it's better to upstream it to LE/master at all?
If it get merged it will be automatic included in CE as well.

**Comment by Portisch** [comment]
Any news on this PR @Kurganov ?

**Comment by Kurganov** [comment]
a lot of work before holidays, not time to test LE build. After 13 dec.

**Comment by Kurganov** [comment]
add PR to LE/master

**Pull request closed without merging**
